### ISSUE TITLE
aarch64的axvm 引入了axhal的依赖

### ISSUE THREAD

**Issue by guoweikang** [arceos-hypervisor/arceos-umhv#22]
这个问题原因在于 现在`EL2` 的异常向量表放在了 `arceos` 的axhal；

修改意见： EL2 的异常向量表应该放在虚拟机软件中 初始化过程应该放在虚拟机初始化流程中

**Comment by hky1999** [comment]
This has been fixed by this [commit](https://github.com/arceos-hypervisor/arm_vcpu/commit/3bce01f2b68c538bda04ddded279925f33ff778c)
